In [ ]:
import numpy as np
import pandas as pd

# import the data required
data = pd.read_csv('/content/survey lung cancer.csv')
print(data.head())

FileNotFoundError: [Errno 2] No such file or directory: '/content/survey lung cancer.csv'

In [ ]:
print(data['GENDER'].unique())
print(data['LUNG_CANCER'].unique())

['M' 'F']
['YES' 'NO']


In [ ]:

# Import label encoder
from sklearn import preprocessing

# label_encoder object knows
# how to understand word labels.
label_encoder = preprocessing.LabelEncoder()

# Encode labels in column 'species'.
data['GENDER']= label_encoder.fit_transform(data['GENDER'])

data['GENDER'].unique()

data['LUNG_CANCER']= label_encoder.fit_transform(data['LUNG_CANCER'])

data['LUNG_CANCER'].unique()


array([1, 0])

In [ ]:
data

GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1   
1         1   74        2               1        1              1   
2         0   59        1               1        1              2   
3         1   63        2               2        2              1   
4         0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304       0   56        1               1        1              2   
305       1   70        2               1        1              1   
306       1   58        2               1        1              1   
307       1   67        2               1        2              1   
308       1   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2         2         2         1                  1   
2                  1         2         1         2                  1   
3                  1         1         1         1                  2   
4                  1         1         1         2                  1   
..               ...       ...       ...       ...                ...   
304                2         2         1         1                  2   
305                1         2         2         2                  2   
306                1         1         2         2                  2   
307                1         2         2         1                  2   
308                1         2         2         2                  2   

     COUGHING  SHORTNESS OF BREATH  SWALLOWING DIFFICULTY  CHEST PAIN  \
0           2                    2                      2           2   
1           1                    2                      2           2   
2           2                    2                      1           2   
3           1                    1                      2           2   
4           2                    2                      1           1   
..        ...                  ...                    ...         ...   
304         2                    2                      2           1   
305         2                    2                      1           2   
306         2                    1                      1           2   
307         2                    2                      1           2   
308         1                    1                      2           1   

     LUNG_CANCER  
0              1  
1              1  
2              0  
3              0  
4              0  
..           ...  
304            1  
305            1  
306            1  
307            1  
308            1  

[309 rows x 16 columns]

In [ ]:
pip install pgmpy

     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 2.0/2.0 MB 8.6 MB/s eta 0:00:00


In [ ]:
data
data['LUNG_CANCER'].unique()


1    270
0     39
Name: LUNG_CANCER, dtype: int64

In [ ]:
data['GENDER'].unique()


array([1, 0])

In [ ]:
data['ALCOHOL CONSUMING'].unique()


array([2, 1])

In [ ]:
data['SMOKING'].unique()


array([1, 2])

In [ ]:
data['CHEST PAIN'].unique()

array([2, 1])

In [ ]:
data

In [ ]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from pgmpy.models import BayesianModel
from pgmpy.estimators import MaximumLikelihoodEstimator
from pgmpy.inference import VariableElimination
data = data
heart_disease = pd.DataFrame(data)
print(heart_disease)

model = BayesianModel([
    ('ALCOHOL CONSUMING', 'LUNG_CANCER'),
    ('GENDER', 'LUNG_CANCER'),
    ('SMOKING', 'LUNG_CANCER'),
    ('LUNG_CANCER', 'YELLOW_FINGERS'),
    ('LUNG_CANCER', 'CHEST PAIN')

])

model.fit(heart_disease, estimator=MaximumLikelihoodEstimator)
HeartDisease_infer = VariableElimination(model)
print('For  enter ALCOHOL CONSUMING 2,1 ')
print('For Gender enter Male:1, Female:0')
print('For CHEST PAIN Yes:1, No:0')
print('For SMOKING 1,2')
print('for yellow fingers 1,2')


q = HeartDisease_infer.query(variables=['LUNG_CANCER'], evidence={
    'ALCOHOL CONSUMING': int(input('Enter ALCOHOL CONSUMING: ')),
    'GENDER': int(input('Enter Gender: ')),
    'CHEST PAIN': int(input('Enter CHEST PAIN: ')),
    'SMOKING': int(input('Enter SMOKING: ')),
    'YELLOW_FINGERS': int(input('Enter YELLOW_FINGERS: ')),

})

print(q)

     GENDER  AGE  SMOKING  YELLOW_FINGERS  ANXIETY  PEER_PRESSURE  \
0         1   69        1               2        2              1   
1         1   74        2               1        1              1   
2         0   59        1               1        1              2   
3         1   63        2               2        2              1   
4         0   63        1               2        1              1   
..      ...  ...      ...             ...      ...            ...   
304       0   56        1               1        1              2   
305       1   70        2               1        1              1   
306       1   58        2               1        1              1   
307       1   67        2               1        2              1   
308       1   62        1               1        1              2   

     CHRONIC DISEASE  FATIGUE   ALLERGY   WHEEZING  ALCOHOL CONSUMING  \
0                  1         2         1         2                  2   
1                  2     

+----------------+--------------------+
| LUNG_CANCER    |   phi(LUNG_CANCER) |
+================+====================+
| LUNG_CANCER(0) |             0.1924 |
+----------------+--------------------+
| LUNG_CANCER(1) |             0.8076 |
+----------------+--------------------+
